# -*- coding: utf-8 -*-
"""genai_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wH8E6yhodBdzhlWcqnI01iZY8aQ0XjP0
"""

!pip install pdfplumber pypdf PyPDF2 transformers datasets accelerate

import os
import re
import torch
import pdfplumber
import datasets
from google.colab import files
from PyPDF2 import PdfReader
from pypdf import PdfReader as SoftPdfReader
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)


# ------------------------------------------------------
# DEVICE
# ------------------------------------------------------
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

#------------------------------------------------------
# UPLOAD PDF
# ------------------------------------------------------
print("Upload your training PDF:")
uploaded = files.upload()
pdf_file = list(uploaded.keys())[0]


# ------------------------------------------------------
# ROBUST PDF EXTRACTION
# ------------------------------------------------------
def extract_text_from_pdf(path):
    text = ""

    # 1) pdfplumber
    try:
        with pdfplumber.open(path) as pdf:
            for page in pdf.pages:
                t = page.extract_text()
                if t:
                    text += t + " "
        if len(text.strip()) > 50:
            print("✔ Extracted using pdfplumber")
            return text
    except:
        pass

    # 2) PyPDF2
    try:
        reader = PdfReader(path)
        for page in reader.pages:
            t = page.extract_text()
            if t:
                text += t + " "
        if len(text.strip()) > 50:
            print("✔ Extracted using PyPDF2")
            return text
    except:
        pass

    # 3) pypdf soft parser
    try:
        reader = SoftPdfReader(path)
        for page in reader.pages:
            t = page.extract_text()
            if t:
                text += t + " "
        if len(text.strip()) > 50:
            print("✔ Extracted using pypdf")
            return text
    except:
        pass

    print("❌ PDF extraction failed.")
    return ""


raw_text = extract_text_from_pdf(pdf_file)
print("Extracted characters:", len(raw_text))

# ------------------------------------------------------
# CLEAN TEXT
# ------------------------------------------------------
def clean_text(t):
    t = t.replace("\r", " ").replace("\n", " ")
    t = re.sub(r"\s+", " ", t)
    return t.strip()

cleaned_text = clean_text(raw_text)


# ------------------------------------------------------
# SPLIT INTO CHUNKS
# ------------------------------------------------------
def chunk_text(text, size=200):
    words = text.split()
    chunks = []
    for i in range(0, len(words), size):
        chunks.append(" ".join(words[i:i+size]))
    return chunks

chunks = chunk_text(cleaned_text, 200)
print("Total chunks:", len(chunks))


# ------------------------------------------------------
# TOKENIZER FIX (IMPORTANT)
# ------------------------------------------------------
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")

if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({"pad_token": "<PAD>"})

# FIX #1 — Prevent tokenizer from expanding or adding new tokens
tokenizer._tokenizer.post_processor = None
tokenizer.model_max_length = 2048
tokenizer.truncation_side = "left"

# ------------------------------------------------------
# DATASET
# ------------------------------------------------------
def tokenize_fn(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=200
    )

dataset = datasets.Dataset.from_dict({"text": chunks})
dataset = dataset.map(tokenize_fn, batched=True)
dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])


# ------------------------------------------------------
# LOAD MODEL + RESIZE EMBEDDINGS
# ------------------------------------------------------
model = AutoModelForCausalLM.from_pretrained("distilgpt2")

# FIX #2 — Resize embeddings AFTER tokenizer is finalized
model.resize_token_embeddings(len(tokenizer))

model.to(device)

# ------------------------------------------------------
# TRAINING
# ------------------------------------------------------
training_args = TrainingArguments(
    output_dir="model_out",
    num_train_epochs=1,
    per_device_train_batch_size=2,
    logging_steps=10,
    save_steps=200,
    learning_rate=5e-5,
    fp16=torch.cuda.is_available(),
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    data_collator=data_collator,
)

print("Training started…")
trainer.train()

# FIX #3 — Resize again after training (ensures perfect alignment)
model.resize_token_embeddings(len(tokenizer))


trainer.save_model("model_out")
tokenizer.save_pretrained("model_out")
print("✔ Training Completed")

# ------------------------------------------------------
# MINI-RAG RETRIEVER
# ------------------------------------------------------
def retrieve_relevant_text(query, chunks, top_n=12):
    query = query.lower()
    results = []

    for chunk in chunks:
        score = sum(w in chunk.lower() for w in query.split())
        results.append((score, chunk))

    results.sort(reverse=True, key=lambda x: x[0])
    return [c for s, c in results[:top_n]]


# ------------------------------------------------------
# 3-PAGE EXTRACTIVE SUMMARIZER
# ------------------------------------------------------
def summarize_topic(topic):
    relevant = retrieve_relevant_text(topic, chunks, top_n=20)
    combined = " ".join(relevant)

    words = combined.split()
    target = 1800  # 3-page summary

    if len(words) > target:
        words = words[:target]

    return " ".join(words)

# ------------------------------------------------------
# QUESTION–ANSWER SYSTEM (FIXED)
# ------------------------------------------------------
def answer_question(question, context_text, max_new_tokens=120):

    # FIX #4 — Safe truncate context to avoid huge prompts
    if len(context_text) > 4000:
        context_text = context_text[-4000:]

    prompt = f"Context: {context_text}\n\nQuestion: {question}\nAnswer:"

    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=2048)
    ids = inputs["input_ids"].to(device)
    mask = inputs["attention_mask"].to(device)

    try:
        output = model.generate(
            input_ids=ids,
            attention_mask=mask,
            max_new_tokens=max_new_tokens,
            temperature=0.6,
            top_k=50,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.pad_token_id,
        )
        return tokenizer.decode(output[0], skip_special_tokens=True)

    except Exception:
        # Fallback safe mode
        safe_context = context_text[-2000:]
        prompt = f"Context: {safe_context}\n\nQuestion: {question}\nAnswer:"
        fallback = tokenizer(prompt, return_tensors="pt").input_ids.to(device)
        output = model.generate(fallback, max_new_tokens=120)
        return tokenizer.decode(output[0], skip_special_tokens=True)

# ------------------------------------------------------
# INTERACTIVE MENU
# ------------------------------------------------------
print("\n=========== MODEL READY ===========")
print("1 = Summarize a topic (~3 pages)")
print("2 = Question–Answer from PDF")
print("exit = Stop program")
print("===================================\n")

while True:
    mode = input("Choose option (1/2/exit): ").strip().lower()

    if mode == "exit":
        break

    if mode == "1":
        topic = input("\nEnter topic to summarize: ")
        summary = summarize_topic(topic)

        print("\n========== SUMMARY ==========\n")
        print(summary)
        print("\n=============================\n")

    elif mode == "2":
        question = input("\nEnter your question: ")

        context_chunks = retrieve_relevant_text(question, chunks, top_n=6)
        context = " ".join(context_chunks)

        print("\n========== ANSWER ==========\n")
        print(answer_question(question, context))
        print("\n=============================\n")

    else:
        print("Invalid option.\n")